// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

@http:ServiceConfig {treatNilableAsOptional: true}
service / on ep0 {
    # Get Bank Statement Accounting
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + bankAccountID - string, GUID
    # Bank account Id
    # + fromDate - date, yyyy-MM-dd 
    # Specifies the start date of the query period. 
    # The maximum range of the query period is 12 months. If the specified query period is more than 12 months the request will be rejected
    # + toDate - date, yyyy-MM-dd 
    # Specifies the end date of the query period. 
    # If the end date is a future date, the request will be rejected
    # + summaryOnly - boolean, true/false
    # The default value is true if no parameter is provided.
    # In summary mode, the response will exclude the computation-heavy LineItems fields from bank transaction, invoice, credit note, prepayment and overpayment data, making the API calls quicker and more efficient
    # + return - returns can be any of following types 
    # http:Ok (Bank statement accounting data)
    # http:BadRequest (BadRequest)
    resource function get BankStatementsPlus/statements(@http:Header {name: "xero-tenant-id"} string xeroTenantId, @http:Query {name: "BankAccountID"} string bankAccountID, @http:Query {name: "FromDate"} string fromDate, @http:Query {name: "ToDate"} string toDate, @http:Query {name: "SummaryOnly"} boolean? summaryOnly) returns BankStatementAccountingResponse|ProblemBadRequest {
        return {
            bankAccountName: "Business Cheque Account",
            bankAccountId: "4f0d7a3e-2c1b-4a8e-9d55-6b1e0c7a9f21",
            bankAccountCurrencyCode: "NZD",
            statements: [
                {
                    statementId: "b7e2c9d4-1a3f-4c58-8e07-52f6a1d3b9c0",
                    startDate: "2025-01-01",
                    endDate: "2025-01-31",
                    startBalance: 10250.00,
                    endBalance: 12480.75,
                    indicativeStartBalance: 10250.00,
                    indicativeEndBalance: 12480.75,
                    importSource: "DirectBankFeed",
                    importedDateTimeUtc: "2025-02-01T02:15:00Z",
                    statementLines: [
                        {
                            statementLineId: "c1d2e3f4-5a6b-4789-9abc-def012345678",
                            transactionDate: "2025-01-15",
                            postedDate: "2025-01-16",
                            amount: 1500.00,
                            payee: "Acme Supplies Ltd",
                            reference: "INV-0042",
                            notes: "January invoice payment",
                            chequeNo: "",
                            'type: "Credit",
                            isReconciled: true,
                            isDeleted: false,
                            isDuplicate: false
                        }
                    ]
                }
            ]
        };
    }

    # Get cash validation
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + balanceDate - date, yyyy-MM-dd 
    # If no parameter is provided, the current date will be used.
    # The ‘balance date’ will return transactions based on the accounting date entered by the user.  Transactions before the balanceDate will be included.
    # The user has discretion as to which accounting period the transaction relates to.
    # The ‘balance date’  will control the latest maximum date of transactions included in the aggregate numbers.  Balance date does not affect the CurrentStatement object, as this will always return the most recent statement before asAtSystemDate (if specified)
    # + asAtSystemDate - date, yyyy-MM-dd 
    # If no parameter is provided, the current date will be used.
    # The ‘as at’ date will return transactions based on the  creation date.  It reflects the date the transactions were entered into Xero, not the accounting date.
    # The ‘as at’ date can not be overridden by the user.  This can be used to estimate a ‘historical frequency of reconciliation’.
    # The ‘as at’ date will affect the current statement in the response, as any candidate statements created after this date will be filtered out.  Thus the current statement returned will be the most recent statement prior to the specified ‘as at’ date.  Be aware that neither the begin date, nor the balance date, will affect the current statement.
    # Note;  information is only presented when system architecture allows, meaning historical cash validation information will be an estimate. In addition, delete events are not aware of the ‘as at’ functionality in this endpoint, meaning that transactions deleted at the time the API is accessed will be considered to always have been deleted
    # + beginDate - date, yyyy-MM-dd 
    # If no parameter is provided, the aggregate results will be drawn from the user’s total history.
    # The ‘begin date’ will return transactions based on the accounting date entered by the user. Transactions after the beginDate will be included.
    # The user has discretion as to which accounting period the transaction relates to
    # + return - returns can be any of following types 
    # http:Ok (Cash validation summary for each account)
    # http:BadRequest (BadRequest)
    resource function get CashValidation(@http:Header {name: "xero-tenant-id"} string xeroTenantId, string? balanceDate, string? asAtSystemDate, string? beginDate) returns CashValidationResponse[]|ProblemBadRequest {
        return [
            {
                accountId: "4f0d7a3e-2c1b-4a8e-9d55-6b1e0c7a9f21",
                statementBalance: {'type: "DEBIT", value: 12480.75},
                statementBalanceDate: "2025-01-31",
                cashAccount: {
                    accountBalance: 12100.50,
                    balanceCurrency: "NZD",
                    startingBalance: 10000.00,
                    unreconciledAmountPos: 450.25,
                    unreconciledAmountNeg: -70.00
                },
                bankStatement: {
                    currentStatement: {
                        startDate: "2025-01-01",
                        endDate: "2025-01-31",
                        startBalance: 10250.00,
                        endBalance: 12480.75,
                        importSourceType: "DirectBankFeed",
                        importedDateTimeUtc: "2025-02-01T02:15:00Z"
                    },
                    statementLines: {
                        totalAmount: 2230.75,
                        reconciledLines: 42,
                        unreconciledLines: 3,
                        earliestReconciledTransaction: "2025-01-02",
                        latestReconciledTransaction: "2025-01-30"
                    }
                }
            }
        ];
    }

    # Get Balance Sheet report
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + balanceDate - Specifies the date for balance sheet report.
    # Format yyyy-MM-dd. If no parameter is provided, the current date will be used
    # + return - returns can be any of following types 
    # http:Ok (Balance sheet report)
    # http:BadRequest (Bad Request)
    # http:ServiceUnavailable (Server Error)
    resource function get FinancialStatements/BalanceSheet(@http:Header {name: "xero-tenant-id"} string xeroTenantId, string? balanceDate) returns BalanceSheetResponse|ProblemBadRequest|ProblemServiceUnavailable {
        return {
            balanceDate: "2025-01-31",
            asset: {
                total: 52000.00,
                accountTypes: [
                    {
                        accountType: "Bank",
                        total: 52000.00,
                        accounts: [{accountID: "a1b2c3d4-0001-4000-8000-000000000001", code: "090", name: "Business Bank Account", reportingCode: "ASS.CUR.CASH", total: 52000.00}]
                    }
                ]
            },
            liability: {
                total: 8000.00,
                accountTypes: [
                    {
                        accountType: "Current Liability",
                        total: 8000.00,
                        accounts: [{accountID: "a1b2c3d4-0002-4000-8000-000000000002", code: "800", name: "Accounts Payable", reportingCode: "LIA.CUR.PAY", total: 8000.00}]
                    }
                ]
            },
            equity: {
                total: 44000.00,
                accountTypes: [
                    {
                        accountType: "Equity",
                        total: 44000.00,
                        accounts: [{accountID: "a1b2c3d4-0003-4000-8000-000000000003", code: "960", name: "Retained Earnings", reportingCode: "EQU.RET", total: 44000.00}]
                    }
                ]
            }
        };
    }

    # Get Cash flow report
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + startDate - Date e.g. yyyy-MM-dd
    # Specifies the start date for cash flow report.
    # If no parameter is provided, the date of 12 months before the end date will be used
    # + endDate - Date e.g. yyyy-MM-dd
    # Specifies the end date for cash flow report.
    # If no parameter is provided, the current date will be used
    # + return - returns can be any of following types 
    # http:Ok (Cash flow report)
    # http:BadRequest (Bad Request)
    # http:ServiceUnavailable (Server Error)
    resource function get FinancialStatements/Cashflow(@http:Header {name: "xero-tenant-id"} string xeroTenantId, string? startDate, string? endDate) returns CashflowResponse|ProblemBadRequest|ProblemServiceUnavailable {
        return {
            startDate: "2024-02-01",
            endDate: "2025-01-31",
            cashBalance: {openingCashBalance: 30000.00, closingCashBalance: 52000.00, netCashMovement: 22000.00},
            cashflowActivities: [
                {
                    name: "Operating activities",
                    total: 22000.00,
                    cashflowTypes: [
                        {
                            name: "Receipts from customers",
                            total: 60000.00,
                            accounts: [{accountId: "a1b2c3d4-0010-4000-8000-000000000010", code: "200", name: "Sales", accountType: "REVENUE", accountClass: "REVENUE", reportingCode: "REV.TRA.GOO", total: 60000.00}]
                        }
                    ]
                }
            ]
        };
    }

    # Get Profit & Loss report
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + startDate - Date e.g. yyyy-MM-dd
    # Specifies the start date for profit and loss report
    # If no parameter is provided, the date of 12 months before the end date will be used
    # + endDate - Date e.g. yyyy-MM-dd
    # Specifies the end date for profit and loss report 
    # If no parameter is provided, the current date will be used
    # + return - returns can be any of following types 
    # http:Ok (Profit and loss report)
    # http:BadRequest (Bad Request)
    resource function get FinancialStatements/ProfitAndLoss(@http:Header {name: "xero-tenant-id"} string xeroTenantId, string? startDate, string? endDate) returns ProfitAndLossResponse|ProblemBadRequest {
        return {
            startDate: "2024-02-01",
            endDate: "2025-01-31",
            netProfitLoss: 18500.00,
            revenue: {
                total: 60000.00,
                accountTypes: [
                    {
                        title: "Revenue",
                        total: 60000.00,
                        accounts: [{accountID: "a1b2c3d4-0010-4000-8000-000000000010", code: "200", name: "Sales", accountType: "REVENUE", reportingCode: "REV.TRA.GOO", total: 60000.00}]
                    }
                ]
            },
            expense: {
                total: 41500.00,
                accountTypes: [
                    {
                        title: "Operating Expenses",
                        total: 41500.00,
                        accounts: [{accountID: "a1b2c3d4-0020-4000-8000-000000000020", code: "469", name: "Rent", accountType: "OVERHEADS", reportingCode: "EXP.OCC.REN", total: 41500.00}]
                    }
                ]
            }
        };
    }

    # Get Trial Balance report
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + endDate - Date e.g. yyyy-MM-dd 
    # Specifies the end date for trial balance report 
    # If no parameter is provided, the current date will be used
    # + return - returns can be any of following types 
    # http:Ok (Trial balance report)
    # http:BadRequest (Bad Request)
    resource function get FinancialStatements/TrialBalance(@http:Header {name: "xero-tenant-id"} string xeroTenantId, string? endDate) returns TrialBalanceResponse|ProblemBadRequest {
        return {
            startDate: "2025-01-01",
            endDate: "2025-01-31",
            accounts: [
                {
                    accountId: "a1b2c3d4-0001-4000-8000-000000000001",
                    accountCode: "090",
                    accountName: "Business Bank Account",
                    accountType: "BANK",
                    accountClass: "ASSET",
                    reportingCode: "ASS.CUR.CASH",
                    status: "ACTIVE",
                    signedBalance: 52000.00,
                    balance: {entryType: "DEBIT", value: 52000.00},
                    accountMovement: {debits: 8000.00, credits: 2000.00, signedMovement: 6000.00, movement: {entryType: "DEBIT", value: 6000.00}}
                }
            ]
        };
    }

    # Get expense by contacts report
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + contactIds - Specifies the customer contacts to be included in the report.
    # If no parameter is provided, all customer contacts will be included
    # + includeManualJournals - Specifies whether to include the manual journals in the report.
    # If no parameter is provided, manual journals will not be included
    # + startDate - Date yyyy-MM-dd
    # Specifies the start date for the report.
    # If no parameter is provided, the date of 12 months before the end date will be used.
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    # + endDate - Date yyyy-MM-dd
    # Specifies the end date for the report.
    # If no parameter is provided, the current date will be used.
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    # + return - returns can be any of following types 
    # http:Ok (Expense by contacts report)
    # http:BadRequest (Bad Request)
    resource function get FinancialStatements/contacts/expense(@http:Header {name: "xero-tenant-id"} string xeroTenantId, string[]? contactIds, boolean? includeManualJournals, string? startDate, string? endDate) returns IncomeByContactResponse|ProblemBadRequest {
        return {
            startDate: "2024-02-01",
            endDate: "2025-01-31",
            total: 25000.00,
            totalDetail: {totalPaid: 20000.00, totalOutstanding: 5000.00, totalCreditedUnApplied: 0.00},
            totalOther: {totalCredited: 120.50, totalVoided: 0.00, totalOutstandingAged: 310.25},
            manualJournals: {total: 0.00},
            contacts: [
                {
                    contactId: "d9e8f7a6-b5c4-4321-8fed-cba987654321",
                    name: "Acme Supplies Ltd",
                    total: 25000.00,
                    totalDetail: {totalPaid: 20000.00, totalOutstanding: 5000.00, totalCreditedUnApplied: 0.00},
                    totalOther: {totalCredited: 120.50, totalVoided: 0.00, totalOutstandingAged: 310.25, transactionCount: 12},
                    accountCodes: ["200", "260"]
                }
            ]
        };
    }

    # Get revenue by contacts report
    #
    # + xeroTenantId - Xero identifier for Tenant
    # + contactIds - Specifies the customer contacts to be included in the report.
    # If no parameter is provided, all customer contacts will be included
    # + includeManualJournals - Specifies whether to include the manual journals in the report.
    # If no parameter is provided, manual journals will not be included
    # + startDate - Date yyyy-MM-dd
    # Specifies the start date for the report.
    # If no parameter is provided, the date of 12 months before the end date will be used.
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    # + endDate - Date yyyy-MM-dd
    # Specifies the end date for the report.
    # If no parameter is provided, the current date will be used.
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    # + return - returns can be any of following types 
    # http:Ok (Revenue by contacts report)
    # http:BadRequest (Bad Request)
    resource function get FinancialStatements/contacts/revenue(@http:Header {name: "xero-tenant-id"} string xeroTenantId, string[]? contactIds, boolean? includeManualJournals, string? startDate, string? endDate) returns IncomeByContactResponse|ProblemBadRequest {
        return {
            startDate: "2024-02-01",
            endDate: "2025-01-31",
            total: 25000.00,
            totalDetail: {totalPaid: 20000.00, totalOutstanding: 5000.00, totalCreditedUnApplied: 0.00},
            totalOther: {totalCredited: 120.50, totalVoided: 0.00, totalOutstandingAged: 310.25},
            manualJournals: {total: 0.00},
            contacts: [
                {
                    contactId: "d9e8f7a6-b5c4-4321-8fed-cba987654321",
                    name: "Acme Supplies Ltd",
                    total: 25000.00,
                    totalDetail: {totalPaid: 20000.00, totalOutstanding: 5000.00, totalCreditedUnApplied: 0.00},
                    totalOther: {totalCredited: 120.50, totalVoided: 0.00, totalOutstandingAged: 310.25, transactionCount: 12},
                    accountCodes: ["200", "260"]
                }
            ]
        };
    }
}

// Service-mode response types. `bal openapi --mode client` collapses 4XX/5XX
// to `error` and never emits these, so they are defined here for the mock only.
public type ProblemBadRequest record {|
    *http:BadRequest;
    Problem body;
|};

public type ProblemServiceUnavailable record {|
    *http:ServiceUnavailable;
    Problem body;
|};

public type Problem record {|
    string detail?;
    ProblemType 'type?;
    string title?;
    int:Signed32 status?;
|};

public type ProblemType "NotSet"|"bank-account-not-found"|"internal-error"|"invalid-application"|"invalid-request"|"organisation-not-found"|"organisation-offline"|"request-timeout"|"service-unavailable"|"unauthorized"|"rate-limit-error";
