// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# The Finance API is a collection of endpoints which customers can use in the course of a loan application, which may assist lenders to gain the confidence they need to provide capital.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.xero.com/finance.xro/1.0") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Get cash validation
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Cash validation summary for each account 
    remote isolated function getCashValidation(GetCashValidationHeaders headers, *GetCashValidationQueries queries) returns CashValidationResponse[]|error {
        string resourcePath = string `/CashValidation`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get Balance Sheet report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Balance sheet report 
    remote isolated function getFinancialStatementBalanceSheet(GetFinancialStatementBalanceSheetHeaders headers, *GetFinancialStatementBalanceSheetQueries queries) returns BalanceSheetResponse|error {
        string resourcePath = string `/FinancialStatements/BalanceSheet`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get Cash flow report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Cash flow report 
    remote isolated function getFinancialStatementCashflow(GetFinancialStatementCashflowHeaders headers, *GetFinancialStatementCashflowQueries queries) returns CashflowResponse|error {
        string resourcePath = string `/FinancialStatements/Cashflow`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get Profit & Loss report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Profit and loss report 
    remote isolated function getFinancialStatementProfitAndLoss(GetFinancialStatementProfitAndLossHeaders headers, *GetFinancialStatementProfitAndLossQueries queries) returns ProfitAndLossResponse|error {
        string resourcePath = string `/FinancialStatements/ProfitAndLoss`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get Trial Balance report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Trial balance report 
    remote isolated function getFinancialStatementTrialBalance(GetFinancialStatementTrialBalanceHeaders headers, *GetFinancialStatementTrialBalanceQueries queries) returns TrialBalanceResponse|error {
        string resourcePath = string `/FinancialStatements/TrialBalance`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get revenue by contacts report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Revenue by contacts report 
    remote isolated function getFinancialStatementContactsRevenue(GetFinancialStatementContactsRevenueHeaders headers, *GetFinancialStatementContactsRevenueQueries queries) returns IncomeByContactResponse|error {
        string resourcePath = string `/FinancialStatements/contacts/revenue`;
        map<Encoding> queryParamEncoding = {"contactIds": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get expense by contacts report
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Expense by contacts report 
    remote isolated function getFinancialStatementContactsExpense(GetFinancialStatementContactsExpenseHeaders headers, *GetFinancialStatementContactsExpenseQueries queries) returns IncomeByContactResponse|error {
        string resourcePath = string `/FinancialStatements/contacts/expense`;
        map<Encoding> queryParamEncoding = {"contactIds": {style: FORM, explode: true}};
        resourcePath = resourcePath + check getPathForQueryParam(queries, queryParamEncoding);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Get Bank Statement Accounting
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Bank statement accounting data 
    remote isolated function getBankStatementAccounting(GetBankStatementAccountingHeaders headers, *GetBankStatementAccountingQueries queries) returns BankStatementAccountingResponse|error {
        string resourcePath = string `/BankStatementsPlus/statements`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        return self.clientEp->get(resourcePath, httpHeaders);
    }
}
