// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

public type CreditNoteResponse record {|
    # Not included in summary mode
    LineItemResponse[] lineItems?;
    # Total of Invoice tax inclusive (i.e. SubTotal + TotalTax); Not included in summary mode
    decimal total?;
    ContactResponse contact?;
    # Xero Identifier of credit note
    string creditNoteId?;
|};

public type StatementBalanceResponse record {|
    # The DEBIT or CREDIT status of the account. Cash accounts in credit have a negative balance
    string 'type?;
    # Total closing balance of the account. This includes both reconciled and unreconciled bank statement lines. The closing balance will always be represented as a positive number, with it’s debit/credit status defined in the statementBalanceDebitCredit field
    decimal value?;
|};

# Represents the Queries record for the operation: getBankStatementAccounting
public type GetBankStatementAccountingQueries record {
    # string, GUID
    # 
    # Bank account Id
    @http:Query {name: "BankAccountID"}
    string bankAccountID;
    # date, yyyy-MM-dd 
    # 
    # Specifies the start date of the query period. 
    # The maximum range of the query period is 12 months. If the specified query period is more than 12 months the request will be rejected
    @http:Query {name: "FromDate"}
    string fromDate;
    # date, yyyy-MM-dd 
    # 
    # Specifies the end date of the query period. 
    # If the end date is a future date, the request will be rejected
    @http:Query {name: "ToDate"}
    string toDate;
    # boolean, true/false
    # 
    # The default value is true if no parameter is provided.
    # 
    # In summary mode, the response will exclude the computation-heavy LineItems fields from bank transaction, invoice, credit note, prepayment and overpayment data, making the API calls quicker and more efficient
    @http:Query {name: "SummaryOnly"}
    boolean summaryOnly?;
};

public type CashflowActivity record {|
    # Total value of the activity type
    decimal total?;
    CashflowType[] cashflowTypes?;
    # Name of the cashflow activity type. It will be either Operating Activities, Investing Activities or Financing Activities
    string name?;
|};

public type PnlAccountType record {|
    # Total movement on this account type
    decimal total?;
    # A list of the movement on each account detail during the query period. Refer to the account detail element below
    PnlAccount[] accounts?;
    # Name of this account type, it will be either Trading Income or Other Income for Revenue section / Direct Cost or Operating Expenses for Expense section
    string title?;
|};

# Represents the Queries record for the operation: getFinancialStatementTrialBalance
public type GetFinancialStatementTrialBalanceQueries record {
    # Date e.g. yyyy-MM-dd 
    # 
    # Specifies the end date for trial balance report 
    # 
    # If no parameter is provided, the current date will be used
    string endDate?;
};

public type TrialBalanceEntry record {|
    # Sign (Debit/Credit) of the movement of balance in the account
    string entryType?;
    # Net movement or net balance in the account
    decimal value?;
|};

public type CurrentStatementResponse record {|
    # Looking at the most recent bank statement, this field indicates the last date which transactions on this statement pertain to. This date is represented in ISO 8601 format
    string endDate?;
    # Looking at the most recent bank statement, this field indicates the balance after the transactions on the statement are applied (note, this is not always populated by the bank in every single instance (~10%))
    decimal endBalance?;
    # Looking at the most recent bank statement, this field indicates when the document was imported into Xero.  This date is represented in ISO 8601 format
    string importedDateTimeUtc?;
    # Looking at the most recent bank statement, this field indicates the source of the data (direct bank feed, file upload, or manual keying)
    string importSourceType?;
    # Looking at the most recent bank statement, this field indicates the first date which transactions on this statement pertain to. This date is represented in ISO 8601 format
    string startDate?;
    # Looking at the most recent bank statement, this field indicates the balance before the transactions on the statement are applied (note, this is not always populated by the bank in every single instance (~10%))
    decimal startBalance?;
|};

public type CashflowAccount record {|
    # ID of the account
    string accountId?;
    # Total amount for the account
    decimal total?;
    # Account code
    string code?;
    # The class of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountClassTypes'>Account Class Types</a>
    string accountClass?;
    # The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>
    string accountType?;
    # Account name
    string name?;
    # Reporting code used for cash flow classification
    string reportingCode?;
|};

public type ContactTotalOther record {|
    # Total credited value for the contact
    decimal totalCredited?;
    # Total voided value for the contact
    decimal totalVoided?;
    # Number of transactions for the contact
    int:Signed32 transactionCount?;
    # Total outstanding invoice value for the contact within the period where the invoices are more than 90 days old
    decimal totalOutstandingAged?;
|};

public type PnlAccountClass record {|
    # Total revenue/expense value
    decimal total?;
    # Contains trading income and other income for revenue section / operating expenses and direct cost for expense section if the data is available for each section. Refer to the account type element below
    PnlAccountType[] accountTypes?;
|};

public type BalanceSheetAccountType record {|
    # Total value of all the accounts in this type
    decimal total?;
    # The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>
    string accountType?;
    # A list of all accounts of this type. Refer to the Account section below for each account element detail
    BalanceSheetAccountDetail[] accounts?;
|};

public type BalanceSheetAccountDetail record {|
    # ID of the account
    string accountID?;
    # Total movement on this account
    decimal total?;
    # Accounting code
    string code?;
    # Account name
    string name?;
    # Reporting code
    string reportingCode?;
|};

# Represents the Queries record for the operation: getFinancialStatementProfitAndLoss
public type GetFinancialStatementProfitAndLossQueries record {
    # Date e.g. yyyy-MM-dd
    # 
    # Specifies the end date for profit and loss report 
    # 
    # If no parameter is provided, the current date will be used
    string endDate?;
    # Date e.g. yyyy-MM-dd
    # 
    # Specifies the start date for profit and loss report
    # 
    # If no parameter is provided, the date of 12 months before the end date will be used
    string startDate?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type CashValidationResponse record {|
    # The Xero identifier for an account
    string accountId?;
    StatementBalanceResponse statementBalance?;
    CashAccountResponse cashAccount?;
    # UTC Date when the last bank statement item was entered into Xero. This date is represented in ISO 8601 format
    string statementBalanceDate?;
    BankStatementResponse bankStatement?;
|};

# Represents the Queries record for the operation: getFinancialStatementBalanceSheet
public type GetFinancialStatementBalanceSheetQueries record {
    # Specifies the date for balance sheet report.
    # 
    # Format yyyy-MM-dd. If no parameter is provided, the current date will be used
    string balanceDate?;
};

public type BankStatementResponse record {|
    StatementLinesResponse statementLines?;
    CurrentStatementResponse currentStatement?;
|};

# Represents the Headers record for the operation: getFinancialStatementBalanceSheet
public type GetFinancialStatementBalanceSheetHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type TotalOther record {|
    # Total credited value
    decimal totalCredited?;
    # Total voided value
    decimal totalVoided?;
    # Total outstanding invoice value within the period where the invoices are more than 90 days old
    decimal totalOutstandingAged?;
|};

public type IncomeByContactResponse record {|
    # Total value
    decimal total?;
    # End date of the report
    string endDate?;
    TotalDetail totalDetail?;
    # Start date of the report
    string startDate?;
    ContactDetail[] contacts?;
    TotalOther totalOther?;
    ManualJournalTotal manualJournals?;
|};

# Represents the Queries record for the operation: getCashValidation
public type GetCashValidationQueries record {
    # date, yyyy-MM-dd 
    # 
    # If no parameter is provided, the aggregate results will be drawn from the user’s total history.
    # 
    # The ‘begin date’ will return transactions based on the accounting date entered by the user. Transactions after the beginDate will be included.
    # The user has discretion as to which accounting period the transaction relates to
    string beginDate?;
    # date, yyyy-MM-dd 
    # 
    # If no parameter is provided, the current date will be used.
    # 
    # The ‘balance date’ will return transactions based on the accounting date entered by the user.  Transactions before the balanceDate will be included.
    # The user has discretion as to which accounting period the transaction relates to.
    # 
    # The ‘balance date’  will control the latest maximum date of transactions included in the aggregate numbers.  Balance date does not affect the CurrentStatement object, as this will always return the most recent statement before asAtSystemDate (if specified)
    string balanceDate?;
    # date, yyyy-MM-dd 
    # 
    # If no parameter is provided, the current date will be used.
    # 
    # The ‘as at’ date will return transactions based on the  creation date.  It reflects the date the transactions were entered into Xero, not the accounting date.
    # The ‘as at’ date can not be overridden by the user.  This can be used to estimate a ‘historical frequency of reconciliation’.
    # 
    # The ‘as at’ date will affect the current statement in the response, as any candidate statements created after this date will be filtered out.  Thus the current statement returned will be the most recent statement prior to the specified ‘as at’ date.  Be aware that neither the begin date, nor the balance date, will affect the current statement.
    # 
    # Note;  information is only presented when system architecture allows, meaning historical cash validation information will be an estimate. In addition, delete events are not aware of the ‘as at’ functionality in this endpoint, meaning that transactions deleted at the time the API is accessed will be considered to always have been deleted
    string asAtSystemDate?;
};

public type BalanceSheetAccountGroup record {|
    # Total value of all the accounts in this type
    decimal total?;
    BalanceSheetAccountType[] accountTypes?;
|};

# Represents the Headers record for the operation: getCashValidation
public type GetCashValidationHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type BankStatementAccountingResponse record {|
    # Name of bank account
    string bankAccountName?;
    # Xero Identifier of bank account
    string bankAccountId?;
    # Currency code of the bank account
    string bankAccountCurrencyCode?;
    # List of bank statements and linked accounting data for the requested period
    StatementResponse[] statements?;
|};

public type StatementResponse record {|
    # Closing statement balance calculated in Xero (= bank account conversion balance plus sum of imported bank statement lines). Note: If indicative statement balance doesn't match imported statement balance for the same date, either the conversion (opening at inception) balance in Xero is wrong or there's an error in the bank statement lines in Xero. Ref: https://central.xero.com/s/article/Compare-the-statement-balance-in-Xero-to-your-actual-bank-balance?userregion=true 
    decimal indicativeEndBalance?;
    # List of statement lines
    StatementLineResponse[] statementLines?;
    # End date of statement
    string endDate?;
    # Closing balance sourced from imported bank statements (if supplied). Note, for manually uploaded statements, this balance is also manual and usually not supplied. Where not supplied, the value will be 0
    decimal endBalance?;
    # Xero Identifier of statement
    string statementId?;
    # Identifies where the statement data in Xero was sourced, 1) direct bank feed, automatically loaded from the bank (eg STMTIMPORTSRC/CBAFEED); 2) indirect bank feed, automatically loaded from a 3rd party provider (eg STMTIMPORTSRC/YODLEE); 3) manually uploaded bank feed (eg STMTIMPORTSRC/CSV) or 4) manually entered statement data (STMTIMPORTSRC/MANUAL)
    string importSource?;
    # Utc date time of when the statement was imported in Xero
    string importedDateTimeUtc?;
    # Start date of statement
    string startDate?;
    # Opening balance sourced from imported bank statements (if supplied). Note, for manually uploaded statements, this balance is also manual and usually not supplied. Where not supplied, the value will be 0
    decimal startBalance?;
    # Opening statement balance calculated in Xero (= bank account conversion balance plus sum of imported bank statement lines). Note: If indicative statement balance doesn't match imported statement balance for the same date, either the conversion (opening at inception) balance in Xero is wrong or there's an error in the bank statement lines in Xero. Ref: https://central.xero.com/s/article/Compare-the-statement-balance-in-Xero-to-your-actual-bank-balance?userregion=true
    decimal indicativeStartBalance?;
|};

public type OverpaymentResponse record {|
    # Not included in summary mode
    LineItemResponse[] lineItems?;
    # Total of Invoice tax inclusive (i.e. SubTotal + TotalTax); Not included in summary mode
    decimal total?;
    # Xero Identifier of overpayment
    string overpaymentId?;
    ContactResponse contact?;
|};

public type TotalDetail record {|
    # Total unapplied credited value within the period
    decimal totalCreditedUnApplied?;
    # Total outstanding invoice value within the period
    decimal totalOutstanding?;
    # Total paid invoice and cash value within the period
    decimal totalPaid?;
|};

public type CashflowType record {|
    # Total value of the activity
    decimal total?;
    # Name of the activity
    string name?;
    # List of the accounts in this activity
    CashflowAccount[] accounts?;
|};

public type PrepaymentResponse record {|
    # Not included in summary mode
    LineItemResponse[] lineItems?;
    # Total of Invoice tax inclusive (i.e. SubTotal + TotalTax); Not included in summary mode
    decimal total?;
    ContactResponse contact?;
    # Xero Identifier of prepayment
    string prepaymentId?;
|};

# Represents the Headers record for the operation: getFinancialStatementTrialBalance
public type GetFinancialStatementTrialBalanceHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type BalanceSheetResponse record {|
    # Balance date of the report
    string balanceDate?;
    BalanceSheetAccountGroup liability?;
    BalanceSheetAccountGroup asset?;
    BalanceSheetAccountGroup equity?;
|};

public type TrialBalanceResponse record {|
    # End date of the report
    string endDate?;
    # Refer to the accounts section below
    TrialBalanceAccount[] accounts?;
    # Start date of the report
    string startDate?;
|};

# Represents the Headers record for the operation: getBankStatementAccounting
public type GetBankStatementAccountingHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type CashflowResponse record {|
    # End date of the report
    string endDate?;
    CashBalance cashBalance?;
    # Break down of cash and cash equivalents for the period
    CashflowActivity[] cashflowActivities?;
    # Start date of the report
    string startDate?;
|};

public type PaymentResponse record {|
    # Date the payment is being made (YYYY-MM-DD) e.g. 2009-09-06
    string date?;
    CreditNoteResponse creditNote?;
    # The amount of the payment
    decimal amount?;
    # The bank amount of the payment
    decimal bankAmount?;
    # Xero Identifier of payment
    string paymentId?;
    OverpaymentResponse overpayment?;
    # Xero Identifier of batch payment. Present if the payment was created as part of a batch
    string batchPaymentId?;
    # Exchange rate when payment is received. Only used for non base currency invoices and credit notes e.g. 0.7500
    decimal currencyRate?;
    InvoiceResponse invoice?;
    PrepaymentResponse prepayment?;
|};

# Represents the Headers record for the operation: getFinancialStatementCashflow
public type GetFinancialStatementCashflowHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type PnlAccount record {|
    # ID of the account
    string accountID?;
    # Total movement on this account
    decimal total?;
    # Account code
    string code?;
    # The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>
    string accountType?;
    # Account name
    string name?;
    # Reporting code (Shown if set)
    string reportingCode?;
|};

public type StatementLineResponse record {|
    # Boolean to show if statement line is reconciled
    boolean isReconciled?;
    # Amount of statement line
    decimal amount?;
    # Notes description of statement line
    string notes?;
    # Cheque number of statement line
    string chequeNo?;
    # List of payments associated with reconciled statement lines
    PaymentResponse[] payments?;
    # Transaction date of statement line
    string transactionDate?;
    # Type of statement line
    string 'type?;
    # Xero Identifier of statement line
    string statementLineId?;
    # Date of when statement line was posted
    string postedDate?;
    # Payee description of statement line
    string payee?;
    # Reference description of statement line
    string reference?;
    # Boolean to show if statement line is deleted
    boolean isDeleted?;
    # Boolean to show if statement line is duplicate
    boolean isDuplicate?;
    # List of bank transactions associated with reconciled statement lines
    BankTransactionResponse[] bankTransactions?;
|};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://identity.xero.com/connect/token";
|};

public type ContactTotalDetail record {|
    # Total unapplied credited value for the contact within the period
    decimal totalCreditedUnApplied?;
    # Total outstanding invoice value for the contact within the period
    decimal totalOutstanding?;
    # Total paid invoice and cash value for the contact within the period
    decimal totalPaid?;
|};

public type BankTransactionResponse record {|
    # Xero Identifier of transaction
    string bankTransactionId?;
    # Date of transaction - YYYY-MM-DD
    string date?;
    # The LineItems element can contain any number of individual LineItem sub-elements. Not included in summary mode
    LineItemResponse[] lineItems?;
    # Amount of transaction
    decimal amount?;
    ContactResponse contact?;
    # Xero Identifier of batch payment. Present if the transaction is part of a batch
    string batchPaymentId?;
|};

# Represents the Headers record for the operation: getFinancialStatementProfitAndLoss
public type GetFinancialStatementProfitAndLossHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type InvoiceResponse record {|
    # Not included in summary mode
    LineItemResponse[] lineItems?;
    # Total of Invoice tax inclusive (i.e. SubTotal + TotalTax); Not included in summary mode
    decimal total?;
    ContactResponse contact?;
    # Xero Identifier of invoice
    string invoiceId?;
|};

# Represents the Queries record for the operation: getFinancialStatementContactsExpense
public type GetFinancialStatementContactsExpenseQueries record {
    # Specifies whether to include the manual journals in the report.
    #             
    # If no parameter is provided, manual journals will not be included
    boolean includeManualJournals?;
    # Date yyyy-MM-dd
    # 
    # Specifies the end date for the report.
    # 
    # If no parameter is provided, the current date will be used.
    #             
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    string endDate?;
    # Specifies the customer contacts to be included in the report.
    # 
    # If no parameter is provided, all customer contacts will be included
    string[] contactIds?;
    # Date yyyy-MM-dd
    # 
    # Specifies the start date for the report.
    #             
    # If no parameter is provided, the date of 12 months before the end date will be used.
    #             
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    string startDate?;
};

public type ContactResponse record {|
    # Xero Identifier of contact
    string contactId?;
    # Full name of contact/organisation
    string contactName?;
|};

public type StatementLinesResponse record {|
    # UTC Date which is the latest transaction date of a statement line for which the reconciled flag is set to FALSE.  This date is represented in ISO 8601 format
    string latestUnreconciledTransaction?;
    # Sum of the amounts of all statement lines where both the reconciled flag is set to TRUE, and the amount is negative
    decimal reconciledAmountNeg?;
    # Sum of the amounts of all statement lines where the amount is negative
    decimal totalAmountNeg?;
    # Sum of the amounts of all statement lines where both the reconciled flag is set to TRUE, and the amount is positive
    decimal reconciledAmountPos?;
    # Sum of the amounts of all statement lines where the amount is positive
    decimal totalAmountPos?;
    # Sum-product of age of statement line in days multiplied by transaction amount, divided by the sum of transaction amount - in for those statement lines in which the reconciled flag is set to FALSE, and the amount is positive. Provides an indication of the age of unreconciled transactions
    decimal avgDaysUnreconciledPos?;
    # Sum-product of age of statement line in days multiplied by transaction amount, divided by the sum of transaction amount - in for those statement lines in which the reconciled flag is set to FALSE, and the amount is negative. Provides an indication of the age of unreconciled transactions
    decimal avgDaysUnreconciledNeg?;
    # UTC Date which is the earliest transaction date of a statement line for which the reconciled flag is set to FALSE.  This date is represented in ISO 8601 format
    string earliestUnreconciledTransaction?;
    # Sum of the amounts of all deleted statement lines.  Transactions may be deleted due to duplication or otherwise
    decimal deletedAmount?;
    # Sum of the amounts of all statement lines.  This is used as a metric of comparison to the unreconciled figures above
    decimal totalAmount?;
    # UTC Date which is the earliest transaction date of a statement line for which the reconciled flag is set to TRUE.  This date is represented in ISO 8601 format
    string earliestReconciledTransaction?;
    # Count of all statement lines where the reconciled flag is set to TRUE
    int:Signed32 reconciledLines?;
    # Sum of the amounts of all statement lines where both the reconciled flag is set to FALSE, and the amount is positive
    decimal unreconciledAmountPos?;
    # Sum of the amounts of all statement lines where both the reconciled flag is set to FALSE, and the amount is negative
    decimal unreconciledAmountNeg?;
    DataSourceResponse dataSource?;
    # Count of all statement lines where the reconciled flag is set to FALSE
    int:Signed32 unreconciledLines?;
    # UTC Date which is the latest transaction date of a statement line for which the reconciled flag is set to TRUE.  This date is represented in ISO 8601 format
    string latestReconciledTransaction?;
|};

# Represents the Headers record for the operation: getFinancialStatementContactsRevenue
public type GetFinancialStatementContactsRevenueHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

# Represents the Headers record for the operation: getFinancialStatementContactsExpense
public type GetFinancialStatementContactsExpenseHeaders record {
    # Xero identifier for Tenant
    @http:Header {name: "xero-tenant-id"}
    string xeroTenantId;
};

public type TrialBalanceMovement record {|
    # Debit amount
    decimal debits?;
    # Credit amount
    decimal credits?;
    # Value of movement. Expense and Asset accounts code debits as positive. Revenue, Liability, and Equity accounts code debits as negative
    decimal signedMovement?;
    TrialBalanceEntry movement?;
|};

public type LineItemResponse record {|
    # Xero Identifier of account
    string accountId?;
    # Account type
    string accountType?;
    # Shown if set
    string reportingCode?;
    # Amount of line item
    decimal lineAmount?;
|};

# Represents the Queries record for the operation: getFinancialStatementCashflow
public type GetFinancialStatementCashflowQueries record {
    # Date e.g. yyyy-MM-dd
    # 
    # Specifies the end date for cash flow report.
    # 
    # If no parameter is provided, the current date will be used
    string endDate?;
    # Date e.g. yyyy-MM-dd
    # 
    # Specifies the start date for cash flow report.
    # 
    # If no parameter is provided, the date of 12 months before the end date will be used
    string startDate?;
};

# Represents the Queries record for the operation: getFinancialStatementContactsRevenue
public type GetFinancialStatementContactsRevenueQueries record {
    # Specifies whether to include the manual journals in the report.
    #             
    # If no parameter is provided, manual journals will not be included
    boolean includeManualJournals?;
    # Date yyyy-MM-dd
    # 
    # Specifies the end date for the report.
    # 
    # If no parameter is provided, the current date will be used.
    #             
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    string endDate?;
    # Specifies the customer contacts to be included in the report.
    # 
    # If no parameter is provided, all customer contacts will be included
    string[] contactIds?;
    # Date yyyy-MM-dd
    # 
    # Specifies the start date for the report.
    #             
    # If no parameter is provided, the date of 12 months before the end date will be used.
    #             
    # It is recommended to always specify both a start date and end date; While the initial range may be set to 12 months, this may need to be reduced for high volume organisations in order to improve latency
    string startDate?;
};

public type CashBalance record {|
    # Net movement of cash and cash equivalents for the period
    decimal netCashMovement?;
    # Opening balance of cash and cash equivalents
    decimal openingCashBalance?;
    # Closing balance of cash and cash equivalents
    decimal closingCashBalance?;
|};

public type ContactDetail record {|
    # Total value for the contact
    decimal total?;
    # ID of the contact associated with the transactions.
    # 
    # Transactions with no contact will be grouped under the special ID: 86793108-198C-46D8-90A3-43C1D12686CE.
    # 
    # Transactions that are receive or spend bank transfers will be grouped under the special ID: 207322B3-6A58-4BE7-80F1-430123914AD6
    string contactId?;
    # Name of the contact associated with the transactions.
    # 
    # If no contact is associated with the transactions this will appear as “None Provided”,
    # 
    # For receive or spend bank transfer transactions, this will appear as “Bank Transfer”
    string name?;
    ContactTotalDetail totalDetail?;
    # A list of account codes involved in transactions
    string[] accountCodes?;
    ContactTotalOther totalOther?;
|};

public type TrialBalanceAccount record {|
    # ID of the account
    string accountId?;
    # Value of balance. Expense and Asset accounts code debits as positive. Revenue, Liability, and Equity accounts code debits as negative
    decimal signedBalance?;
    TrialBalanceMovement accountMovement?;
    # Customer defined alpha numeric account code e.g 200 or SALES
    string accountCode?;
    # The class of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountClassTypes'>Account Class Types</a>
    string accountClass?;
    TrialBalanceEntry balance?;
    # Name of the account
    string accountName?;
    # The type of the account. See <a href='https://developer.xero.com/documentation/api/types#AccountTypes'>Account Types</a>
    string accountType?;
    # Reporting code (Shown if set)
    string reportingCode?;
    # Accounts with a status of ACTIVE can be updated to ARCHIVED. See <a href='https://developer.xero.com/documentation/api/types#AccountStatusCodes'>Account Status Codes</a>
    string status?;
|};

public type DataSourceResponse record {|
    # Sum of the amounts of all statement lines where the source of the data was a direct bank feed in to Xero via an API integration.   This could be from a bank or aggregator.   This gives an indication on the certainty of correctness of the data
    decimal directBankFeed?;
    # Sum of the amounts of all statement lines where the source of the data was a file manually uploaded in to Xero.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included
    decimal fileUploadNeg?;
    # Sum of the amounts of all statement lines where the source of the data was unknown.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included
    decimal otherNeg?;
    # Sum of the amounts of all statement lines where the source of the data was unknown.   This gives an indication on the certainty of correctness of the data
    decimal other?;
    # Sum of the amounts of all statement lines where the source of the data was a file manually uploaded in to Xero.   This gives an indication on the certainty of correctness of the data. Only positive transactions are included
    decimal fileUploadPos?;
    # Sum of the amounts of all statement lines where the source of the data was unknown.   This gives an indication on the certainty of correctness of the data.  Only positive transactions are included
    decimal otherPos?;
    # Sum of the amounts of all statement lines where the source of the data was a direct bank feed in to Xero via an API integration.   This could be from a bank or aggregator.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included
    decimal directBankFeedNeg?;
    # Sum of the amounts of all statement lines where the source of the data was manually input in to Xero.   This gives an indication on the certainty of correctness of the data.  Only negative transactions are included
    decimal manualNeg?;
    # Sum of the amounts of all statement lines where the source of the data was a direct bank feed in to Xero via an API integration.   This could be from a bank or aggregator.  This gives an indication on the certainty of correctness of the data.  Only positive transactions are included
    decimal directBankFeedPos?;
    # Sum of the amounts of all statement lines where the source of the data was a file manually uploaded in to Xero.   This gives an indication on the certainty of correctness of the data
    decimal fileUpload?;
    # Sum of the amounts of all statement lines where the source of the data was manually input in to Xero.   This gives an indication on the certainty of correctness of the data
    decimal manual?;
    # Sum of the amounts of all statement lines where the source of the data was manually input in to Xero.   This gives an indication on the certainty of correctness of the data. Only positive transactions are included
    decimal manualPos?;
|};

public type ManualJournalTotal record {|
    # Total value of manual journals
    decimal total?;
|};

public type CashAccountResponse record {|
    # Total value of transactions in the journals which are not reconciled to bank statement lines, and have a positive (debit) value
    decimal unreconciledAmountPos?;
    # Total value of transactions in the journals which are not reconciled to bank statement lines, and have a negative (credit) value
    decimal unreconciledAmountNeg?;
    # Current cash at bank accounting value from the journals
    decimal accountBalance?;
    # Currency which the cashAccount transactions relate to
    string balanceCurrency?;
    # Starting (or historic) balance from the journals (manually keyed in by users on account creation - unverified)
    decimal startingBalance?;
|};

public type ProfitAndLossResponse record {|
    PnlAccountClass revenue?;
    # End date of the report
    string endDate?;
    # Net profit loss value
    decimal netProfitLoss?;
    PnlAccountClass expense?;
    # Start date of the report
    string startDate?;
|};
